Repository rosineygp/mkdkr, pull requests merged in 2020-03, with the labels that each got.

#91 Feat/requirements verify
  .mkdkr
  Makefile
  test/unit
  test/unit_requirements
Labels: enhancement

#95 docs: add table for collections
  README.md
Labels: documentation

#96 feat: add circle-ci parallel jobs
  .circleci/config.yml
Labels: enhancement

#98 Fix/force mkdkr version
  .mkdkr
  mkdkr.csv
Labels: bug, enhancement

#99 refactor: move handler tmp files to _tmp_dir function
  .mkdkr
Labels: refactor

#100 Fix/docker run failed
  .mkdkr
Labels: bug, refactor

#101 refactor: create a function for clone operation
  .mkdkr
  test/unit_remote_include
Labels: bug, refactor

#102 Refactor/improve functions
  .mkdkr
Labels: refactor

#103 Feat/mult service
  .mkdkr
  Makefile
  README.md
  examples/service.mk
  test/unit_create_instance
Labels: documentation, enhancement, refactor

#104 Fix/docker base image
  Dockerfile
Labels: bug

#105 feat: update gitlab-ci and mkdkr_exporter
  .gitlab-ci.yml
  mkdkr.csv
Labels: enhancement

#106 docs: docker pull badge
  README.md
Labels: documentation

#108 fix: send result of times to stderr
  .mkdkr
Labels: bug

#109 test: test color prints
  test/unit
  test/unit_colors
Labels: enhancement

#111 feat: add local script pipeline
  pipeline.sh
Labels: enhancement

#112 feat: passing network args from variable MKDKR_NETWORK_ARGS
  .mkdkr
  README.md
Labels: bug, enhancement

#114 Fix: typos in README.md
  README.md
Labels: documentation

#116 docs: include contrib guide
  CONTRIBUTING.md
Labels: documentation
